unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

# Rebind Leader
set -g prefix C-s

# Mouse Support
set -g mouse on

setw -g mode-keys vi
# set-option -g status-position top

# Navigation
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Vertical split in current pane's directory
bind '"' split-window -v -c "#{pane_current_path}"
# Horizontal split in current pane's directory
bind % split-window -h -c "#{pane_current_path}"
# New window in current pane's directory
bind c new-window    -c "#{pane_current_path}"

# PLUGINs
# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# THEME - minimal-tmux-status
set -g @plugin 'niksingh710/minimal-tmux-status'

# Theme configuration (optional - these are nice defaults)
set -g @minimal-tmux-justify "centre"
set -g @minimal-tmux-indicator-str "JP"
set -g @minimal-tmux-indicator true
set -g @minimal-tmux-status "bottom"

# Enable left and right status bar
set -g @minimal-tmux-right true
set -g @minimal-tmux-left true

# Use rounded indicators
set -g @minimal-tmux-use-arrow true
set -g @minimal-tmux-right-arrow ""
set -g @minimal-tmux-left-arrow ""

run '~/.tmux/plugins/tpm/tpm'
